filter_finder:
    max_attempts: 100
    main_results_dir: tmp/output/filter_finder/
    results_base_dir: tmp/output/filter_finder/useless_test
    save_plot: true
    show_plots: true
    algorithm_configs:
        algorithm: gradient_descent
        #results_base_dir: tmp/output/filter_finder/testruns\patch_filter_4_points_2020_03_02_172058    #Not required, because algorithm is called with is_main=False flag
        hyperparameters:
            nr_epochs: 1000
            batch_size: 100
            learning_rate: 0.001
            learning_rate: 0.001                                                         # With noise, 0.0005 seems like a good value for patch filtering.
            loss_function: entropy_hard_boundaries
            optimizer: adam
            #betas: [0.99, 0.999]                                                           # Beta values used for the Adam optimizer. When not spupplied, torch default values (0.9, 0.999) will be used.
            stop_threshold: -1000
        processor:
            architecture: single_device
            platform: simulation
            simulation_type: neural_network
            network_type: IOnet                                                           #IOnet, dnpu, ...
            IOinfo:                                                                         # Only necessary when calling an instance of IOnet
                output_high: 76             #max and minimum info of the training daata. Outside will be regularized by adding a loss.
                output_low: -150
                mode: multi_scaler
            torch_model_dict: tmp/input/models/model_2020.pt
            use_noise: false
            input_indices: [1,2]
            input_electrode_no: 7                                                           # The total amount of input electrodes. Required for the processor to determine the control electrodes.
            waveform:
                amplitude_lengths: 1                                                        # In simulation, you can set this to 0 to just feed one datapoint.
                slope_lengths: 0
                output_clipping_value: 3.55
        checkpoints:
            use_checkpoints: false
            save_dir: algorithm_checkpoints
            save_interval: 100
            live_plot: false
            live_plot_interval: 8
    boolean_gate_test:
        validation:
            processor:
                waveform:
                    amplitude_lengths: 1
                    slope_lengths: 0
                    output_clipping_value: 3.55
        algorithm_configs:
            algorithm: gradient_descent
            processor:
                auto_generate_inputs: true
                platform: simulation
                input_indices: [1,2]
                input_electrode_no: 7
                num_elec: 8
                waveform:
                    use_waveform: true
                    amplitude_lengths: 1
                    slope_lengths: 0
                    output_clipping_value: 3.55
