name: bspytasks
dependencies:
  - python=3.6
  - pip
  - git
  - openpyxl
  - numpy
  - pandas
  - matplotlib
  - xlsxwriter
  - scipy
  - ipython
  - pip:
    - git+https://github.com/BraiNEdarwin/brainspy-processors.git
    - git+https://github.com/BraiNEdarwin/brainspy-algorithms.git
    - git+https://github.com/BraiNEdarwin/brainspy-tasks.git
